stages:
  retrieve:
    cmd: python src-preparation/1_retrieve_dataset.py
    deps:
      - src-preparation/1_retrieve_dataset.py
      - data/openfoodfacts-products.jsonl.gz
    outs:
      - gen/off_selected_fields_filtered.csv
      - gen/openfoodfacts_10records.txt

  prepare:
    cmd: Rscript src-preparation/2_prepare_data.R
    deps:
      - src-preparation/2_prepare_data.R
      - gen/off_selected_fields_filtered.csv
    outs:
      - gen/main_data.csv
      - gen/label_freq.csv
      - gen/labels_long.csv
      - gen/categories_long.csv
      - gen/categories_wide.csv

  category_mapping:
    cmd: Rscript src-preparation/3_category_mapping.R
    deps:
      - src-preparation/3_category_mapping.R
      - gen/main_data.csv
      - gen/categories_wide.csv
      - gen/categories_long.csv
    outs:
      - gen/rule_hits.csv
      - gen/cat_harmonized_freq.csv
      - gen/category_mapped_data.csv
      - gen/category_mapped_filtered.csv

  label_mapping:
    cmd: Rscript src-preparation/4_label_mapping.R
    deps:
      - src-preparation/4_label_mapping.R
      - gen/category_mapped_filtered.csv
      - gen/labels_long.csv
      - data/labels_mapping.xlsx
    outs:
      - gen/label_mapped_filtered.csv
      - gen/labels_def.csv
      - gen/labels_string_df.csv

  final_dataset:
    cmd: Rscript src-preparation/5_create_final_dataset.R
    deps:
      - src-preparation/5_create_final_dataset.R
      - gen/label_mapped_filtered.csv
      - gen/off_selected_fields_filtered.csv
    outs:
      - results/data_def.csv
      - gen/data_def_cat1.csv
      - gen/data_def_cat12.csv
      - gen/data_def_cat123.csv
      - gen/data_def_cat3.csv
      - gen/data_def_cat23.csv

  explore:
    cmd: Rscript src-preparation/6_explore_final_dataset.R
    deps:
      - src-preparation/6_explore_final_dataset.R
      - results/data_def.csv
      - gen/label_freq.csv
      - gen/labels_long.csv
    outs:
      - plots/

  split_data:
    cmd: python src-modeling/1.0_split_dataset.py
    deps:
      - src-modeling/1.0_split_dataset.py
      - results/data_def.csv
    outs:
      - gen/main_stratify_counts.csv
      - gen/main_stratify_counts_after_threshold.csv
      - gen/data_def_train.csv
      - gen/data_def_test.csv

  tag_test_set:
    cmd: python src-modeling/1.1_test_dataset.py
    deps:
      - src-modeling/1.1_test_dataset.py
      - gen/data_def_test.csv
    outs:
      - gen/data_def_test.csv:
          cache: true