baseline:
  solver: "saga"
  random_state: 42

rf_nutri:
  base:
    random_state: 42
    n_jobs: -1
    max_depth: null
    min_samples_split: 10
    min_samples_leaf: 1
    class_weight: "balanced"
    max_features: "log2"
  phase1:
    n_estimators: 50
  phase2:
    n_estimators: 100
  phase3:
    n_estimators: 200

rf_nova:
  base:
    random_state: 42
    n_jobs: -1
    max_depth: null
    min_samples_split: 10
    min_samples_leaf: 1
    class_weight: "balanced"
  phase1:
    n_estimators: 50
    max_features: "sqrt"
  phase2:
    n_estimators: 100
    max_features: "log2"
  phase3:
    n_estimators: 200
    max_features: "log2"